[project]
name = "what"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "azure-quantum>=2.1.1",
    "qsharp>=1.8.0",
]
